// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ72xk7kXRzBqAqWgoP7JKK3JL9JDIZF4',
    appId: '1:221409888548:web:85e306cc50e8b228590bb1',
    messagingSenderId: '221409888548',
    projectId: 'workshop-2023-apprise',
    authDomain: 'workshop-2023-apprise.firebaseapp.com',
    storageBucket: 'workshop-2023-apprise.appspot.com',
    measurementId: 'G-MFLB91QWKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3znRNd5-0Vljad3VMjSScVD3JM4IHhM',
    appId: '1:221409888548:android:12cd297a0ffdaed2590bb1',
    messagingSenderId: '221409888548',
    projectId: 'workshop-2023-apprise',
    storageBucket: 'workshop-2023-apprise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8T_c7KzW80OPK8yiKZ813McPkkSj5sU8',
    appId: '1:221409888548:ios:71813afcf27ddca8590bb1',
    messagingSenderId: '221409888548',
    projectId: 'workshop-2023-apprise',
    storageBucket: 'workshop-2023-apprise.appspot.com',
    iosClientId: '221409888548-l7a3ng4g57lo7bbn0pd9h4gtrmelgbd4.apps.googleusercontent.com',
    iosBundleId: 'com.appriseconf.workshop23.workshop22032023',
  );
}
